# User config
author: "Paul Amouroux"
tagline: "Artrópodos diurnos y nocturnos de Valle Exploradores (Región: Aysén)"
description: "Fichas descriptivas"
keywords: "Bahia Exploradores, Entomología"
email: "zosterops1981@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/artropodos_valleexploradores"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
